<<<<<<< HEAD
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('1', '3', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Bronze PPO 201');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('2', '3', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Bronze PPO 202');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('3', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Bronze PPO 302');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('4', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Bronze PPO 502');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('5', '3', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Bronze PPO 601');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('6', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Bronze PPO 701');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('7', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Bronze PPO 705');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('8', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Bronze PPO 708');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('9', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Gold PPO 204');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('10', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Gold PPO 707');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('11', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Silver PPO 203');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('12', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Silver PPO 303');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('13', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Silver PPO 706');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('14', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield - Blue Advantage HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('15', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield – Blue Advantage HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('16', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield - Blue Advantage HMO ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('17', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield - Blue Advantage HMO ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('18', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield – Blue Choice Options');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('19', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield - Blue Choice Options (Tier 1)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('20', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield - Blue Choice Options (Tier 1) ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('21', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield - Blue Choice Options (Tier 1) ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('22', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield - Blue Choice PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('23', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield - HMOI');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('24', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield - HMOI ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('25', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield – HMOI ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('26', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield – HMOI ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('27', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield - HMOI ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('28', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield - PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('29', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield – PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('30', '1', 'Blue Cross Blue Shield', '3', 'Blue Precision Bronze HMO 205');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('31', '1', 'Blue Cross Blue Shield', '3', 'Blue Precision Bronze HMO 701 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('32', '1', 'Blue Cross Blue Shield', '3', 'Blue Precision Bronze HMO 708');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('33', '1', 'Blue Cross Blue Shield', '3', 'Blue Precision Gold HMO 207');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('34', '1', 'Blue Cross Blue Shield', '3', 'Blue Precision Gold HMO 703 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('35', '1', 'Blue Cross Blue Shield', '3', 'Blue Precision Gold HMO 707');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('36', '1', 'Blue Cross Blue Shield', '3', 'Blue Precision Silver HMO 206');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('37', '1', 'Blue Cross Blue Shield', '3', 'Blue Precision Silver HMO 306');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('38', '1', 'Blue Cross Blue Shield', '3', 'Blue Precision Silver HMO 704 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('39', '1', 'Blue Cross Blue Shield', '3', 'Blue Precision Silver HMO 706');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('40', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Bronze PPO  201');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('41', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Bronze PPO  202');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('42', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Bronze PPO  601 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('43', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Bronze PPO  701 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('44', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Bronze PPO  708');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('45', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Gold PPO  204 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('46', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Gold PPO  707');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('47', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Silver PPO  203');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('48', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Silver PPO  303');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('49', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Silver PPO  706');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('50', '1', 'Blue Cross Blue Shield', '3', 'Blue Choice Preferred Silver PPO  801 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('51', '1', 'Aetna', '1', 'Aetna - HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('52', '1', 'Aetna', '1', 'Aetna – HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('53', '1', 'Aetna', '1', 'Aetna - Open Access HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('54', '1', 'Aetna', '1', 'Aetna – Open Access HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('55', '1', 'Aetna', '1', 'Aetna - PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('56', '1', 'Aetna', '1', 'Aetna – PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('57', '1', 'Aetna', '1', 'Aetna Choice POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('58', '1', 'Aetna', '1', 'Aetna Choice POS II');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('59', '1', 'Aetna', '1', 'Aetna Elect Choice');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('60', '1', 'Aetna', '1', 'Aetna EPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('61', '1', 'Aetna', '1', 'Aetna Health Network Only');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('62', '1', 'Aetna', '1', 'Aetna Health Network Option');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('63', '1', 'Aetna', '1', 'Aetna HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('64', '1', 'Aetna', '1', 'Aetna Illinois Preferred Plan');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('65', '1', 'Aetna', '1', 'Aetna Managed Choice POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('66', '1', 'Aetna', '1', 'Aetna Managed Choice POS>');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('67', '1', 'Aetna', '1', 'Aetna NAP');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('68', '1', 'Aetna', '1', 'Aetna Open Access Elect Choice');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('69', '1', 'Aetna', '1', 'Aetna Open Access HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('70', '1', 'Aetna', '1', 'Aetna Open Access Managed Choice');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('71', '1', 'Aetna', '1', 'Aetna Open Choice PPO ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('72', '1', 'Aetna', '1', 'Aetna Performance Network');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('73', '1', 'Aetna', '1', 'Aetna Performance Network (Tier 2)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('74', '1', 'Aetna', '1', 'Aetna Premier Care Network');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('75', '1', 'Aetna', '1', 'Aetna Premier Care Network ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('76', '1', 'Aetna', '1', 'Aetna Premier Care Network Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('77', '1', 'Aetna', '1', 'Aetna Premier Care Network Plus ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('78', '1', 'Aetna', '1', 'Aetna Prime HMO-POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('79', '1', 'Aetna', '1', 'Aetna QPOS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('80', '1', 'Aetna', '1', 'Aetna Savings Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('81', '1', 'Aetna', '1', 'Aetna Savings Plus ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('82', '1', 'Aetna', '1', 'Aetna Savings Plus (Tier 2)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('83', '1', 'Aetna', '1', 'Aetna Savings Plus (Tier 2)br />');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('84', '1', 'Aetna', '1', 'Aetna Select');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('85', '1', 'Aetna', '1', 'Aetna Student Health');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('86', '1', 'Aetna', '1', 'Aetna Traditional Choice');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('87', '1', 'Aetna', '1', 'Aetna Voluntary Group Medical Plan (Indemnity Plan)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('88', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('89', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield - HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('90', '1', 'Blue Cross Blue Shield', '3', 'Blue Cross Blue Shield – HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('92', '2', 'CHAMPUS', '16', 'CHAMPUS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('93', '1', 'Cigna', '4', 'Cigna - Choice Fund Open Access Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('94', '1', 'Cigna', '4', 'Cigna – Choice Fund Open Access Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('95', '1', 'Cigna', '4', 'Cigna - ChoiceCare PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('96', '1', 'Cigna', '4', 'Cigna – ChoiceCare PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('97', '1', 'Cigna', '4', 'Cigna - EPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('98', '1', 'Cigna', '4', 'Cigna – EPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('99', '1', 'Cigna', '4', 'Cigna - Global Health Benefits');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('100', '1', 'Cigna', '4', 'Cigna – Global Health Benefits');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('101', '1', 'Cigna', '4', 'Cigna - GWH POS Open Access Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('102', '1', 'Cigna', '4', 'Cigna – GWH POS Open Access Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('103', '1', 'Cigna', '4', 'Cigna - HMO (or POS)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('104', '1', 'Cigna', '4', 'Cigna – HMO (or POS)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('105', '1', 'Cigna', '4', 'Cigna - HMO (or POS) Open Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('106', '1', 'Cigna', '4', 'Cigna – HMO (or POS) Open Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('107', '1', 'Cigna', '4', 'Cigna - Local Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('108', '1', 'Cigna', '4', 'Cigna - Network Open Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('109', '1', 'Cigna', '4', 'Cigna – Network Open Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('110', '1', 'Cigna', '4', 'Cigna - Network POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('111', '1', 'Cigna', '4', 'Cigna – Network POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('112', '1', 'Cigna', '4', 'Cigna - One Health HMO eff 4/1/19');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('113', '1', 'Cigna', '4', 'Cigna - Open Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('114', '1', 'Cigna', '4', 'Cigna – Open Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('115', '1', 'Cigna', '4', 'Cigna - Open Access Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('116', '1', 'Cigna', '4', 'Cigna – Open Access Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('117', '1', 'Cigna', '4', 'Cigna - POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('118', '1', 'Cigna', '4', 'Cigna – POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('119', '1', 'Cigna', '4', 'Cigna - PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('120', '1', 'Cigna', '4', 'Cigna – PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('121', '1', 'Cigna', '4', 'Cigna - Shared Administration PPO and OAP');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('122', '1', 'Cigna', '4', 'Cigna – Shared Administration PPO and OAP');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('123', '1', 'Cigna', '4', 'Cigna Courage Medicare (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('124', '1', 'Cigna', '4', 'Cigna Plus Bronze CMS Standard');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('125', '1', 'Cigna', '4', 'Cigna Plus Gold CMS Standard - Rx Copay');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('126', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 0-2*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('127', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 0-3*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('128', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 0-4A*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('129', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 0-4B*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('130', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 0A*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('131', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 0B*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('132', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 100-4 Rx Copay*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('133', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 1900 Enhanced Diabetes Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('134', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 2000-3*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('135', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 2500-2 Rx Copay*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('136', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 3000 Rx Copay*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('137', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 3000-2 Enhanced Diabetes Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('138', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 350-3 Rx Copay*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('139', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 3550-2 Enhanced Asthma COPD Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('140', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 3800 Enhanced Diabetes Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('141', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 3800-2*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('142', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 40-4 Enhanced Diabetes Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('143', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 4200 Enhanced Asthma COPD Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('144', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 5000 Rx Copay*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('145', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 50-4 Enhanced Asthma COPD Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('146', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 6000*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('147', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 600-3 Enhanced Diabetes Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('148', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 6150-2*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('149', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 650-4*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('150', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 6800 Enhanced Diabetes Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('151', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 700-3*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('152', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 750 Rx Copay*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('153', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 750-3 Enhanced Asthma COPD Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('154', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine 8000*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('155', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine Diabetes 7600 Enhanced Asthma COPD Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('156', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine HSA 7050*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('157', '1', 'Cigna', '4', 'Cigna Plus Northwestern Medicine will not be available for residents of Cook County. However, residents of DuPage, Kane, Lake and McHenry counties will still have coverage in Cook County if they receive care at Northwestern Memorial Hospital.');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('158', '1', 'Cigna', '4', 'Cigna Plus Silver CMS Standard');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('159', '1', 'Cigna', '4', 'Cigna Plus Silver-2 CMS Standard');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('160', '1', 'Cigna', '4', 'Cigna Plus Silver-3 CMS Standard');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('161', '1', 'Cigna', '4', 'Cigna Plus Silver-4 CMS Standard');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('162', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine (Effective 1/1/2021)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('163', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine 1000**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('164', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine 1250 - Northwestern Medicine Only**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('165', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine 2000 (Effective 1/1/2022)*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('166', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine 2000 (Effective 1/1/2023)*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('167', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine 3000**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('168', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine 3500 Diabetes Care**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('169', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine 4400 (Effective 1/1/2022)*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('170', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine 4400 (Effective 1/1/2023)*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('171', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine 5000**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('172', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine 6000**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('173', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine 7000**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('174', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine 750**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('175', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine 7500**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('176', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine 8500**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('177', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine 8700**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('178', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine Asthma/COPD 4200**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('179', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine Bronze 5000 Indiv Med Deductible - Rx Copay');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('180', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine Diabetes 6800**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('181', '1', 'Cigna', '4', 'Cigna Plus With Northwestern Medicine Plan 0**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('182', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine Silver 3000 Indiv Med Deductible - Rx Copay');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('183', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine Silver 5000 Indiv Med Deductible');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('184', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine Silver-2 2500 Indiv Med Deductible - Rx Copay');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('185', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine Silver-2 3800 Indiv Med Deductible');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('186', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine Silver-3 350 Indiv Med Deductible - Rx Copay');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('187', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine Silver-3 700 Indiv Med Deductible');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('188', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine Silver-4 0 Indiv Med Deductible');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('189', '1', 'Cigna', '4', 'Cigna Plus with Northwestern Medicine Silver-4 100 Indiv Med Deductible - Rx Copay');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('190', '1', 'Cigna', '4', 'Cigna Preferred Medicare (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('191', '1', 'Cigna', '4', 'Cigna Simple Choice 0-4C');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('192', '1', 'Cigna', '4', 'Cigna Simple Choice 2000');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('193', '1', 'Cigna', '4', 'Cigna Simple Choice 5700-2');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('194', '1', 'Cigna', '4', 'Cigna Simple Choice 5800');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('195', '1', 'Cigna', '4', 'Cigna Simple Choice 7500');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('196', '1', 'Cigna', '4', 'Cigna Simple Choice 9100');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('197', '1', 'Cigna', '4', 'Cigna True Choice Courage Medicare (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('198', '1', 'Cigna', '4', 'Cigna True Choice Medicare (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('199', '1', 'Cigna', '4', 'Cigna True Choice Plus Medicare (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('200', '1', 'Cigna', '4', 'Cigna True Choice Savings Medicare (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('201', '1', 'Cigna', '4', 'Cigna – Local Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('202', '4', 'Medicaid', '18', 'CountyCare');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('203', '1', 'Health Alliance', '9', 'Health Alliance');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('204', '1', 'Health Alliance', '9', 'Health Alliance Marketplace Plans HMO ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('205', '1', 'Health Alliance', '9', 'Health Alliance  ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('206', '1', 'HFN', '10', 'HFN - EPO (HFN20)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('207', '1', 'HFN', '10', 'HFN - Platinum');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('208', '1', 'HFN', '10', 'HFN - PPO (HFN10)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('209', '1', 'HFN', '10', 'HFN – PPO (HFN10)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('210', '1', 'HFN', '10', 'HFN - Workers Compensation Program/Network');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('211', '1', 'Humana', '11', 'Humana – Choice Care PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('212', '1', 'Humana', '11', 'Humana - Choice POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('213', '1', 'Humana', '11', 'Humana – Choice POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('214', '1', 'Humana', '11', 'Humana - ChoiceCare PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('215', '1', 'Humana', '11', 'Humana - EPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('216', '1', 'Humana', '11', 'Humana – EPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('217', '1', 'Humana', '11', 'Humana - HMO Premier');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('218', '1', 'Humana', '11', 'Humana – HMO Premier');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('219', '1', 'Humana', '11', 'Humana - HMO Select');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('220', '1', 'Humana', '11', 'Humana – HMO Select');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('221', '1', 'Humana', '11', 'Humana - Illinois Platinum HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('222', '1', 'Humana', '11', 'Humana – Illinois Platinum HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('223', '1', 'Humana', '11', 'Humana – National  Preferred POS – Open Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('224', '1', 'Humana', '11', 'Humana - National Preferred POS - Open Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('225', '1', 'Humana', '11', 'Humana - PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('226', '1', 'Humana', '11', 'Humana – PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('227', '1', 'Humana', '11', 'Humana - Preferred PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('228', '1', 'Humana', '11', 'Humana – Preferred PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('229', '1', 'Humana', '11', 'Humana Behavioral Health');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('230', '1', 'Humana', '11', 'Humana HMO Gold Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('231', '1', 'Humana', '11', 'Humana Honor PPO (Veterans Plan)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('232', '1', 'Humana', '11', 'Humana PFFS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('233', '1', 'Humana', '11', 'Humana PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('234', '4', 'Medicaid', '18', 'Medicaid');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('235', '5', 'Medicare', '17', 'Medicare');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('236', '4', 'Medicaid', '18', 'Meridian');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('237', '9', 'Meridian', '25', 'Meridian Complete');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('238', '2', 'Tricare East', '20', 'TriCare East Administered by Humana Military');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('239', '1', 'United', '21', 'United Behavioral Health – Optum');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('240', '1', 'United', '21', 'United Healthcare - All Savers');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('241', '1', 'United', '21', 'United Healthcare – All Savers');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('242', '1', 'United', '21', 'United Healthcare - Choice');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('243', '1', 'United', '21', 'United Healthcare – Choice');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('244', '1', 'United', '21', 'United Healthcare - Choice Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('245', '1', 'United', '21', 'United Healthcare – Choice Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('246', '1', 'United', '21', 'United Healthcare - Core');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('247', '1', 'United', '21', 'United Healthcare – Core');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('248', '1', 'United', '21', 'United Healthcare – HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('249', '1', 'United', '21', 'United Healthcare - HMO Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('250', '1', 'United', '21', 'United Healthcare – HMO Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('251', '1', 'United', '21', 'United Healthcare - HMO Plus ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('252', '1', 'United', '21', 'United Healthcare - HMO ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('253', '1', 'United', '21', 'United Healthcare - Navigate');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('254', '1', 'United', '21', 'United Healthcare – Navigate');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('255', '1', 'United', '21', 'United Healthcare – Open Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('256', '1', 'United', '21', 'United Healthcare - Open Access ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('257', '1', 'United', '21', 'United Healthcare - Options PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('258', '1', 'United', '21', 'United Healthcare – Options PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('259', '1', 'United', '21', 'United Healthcare - Select');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('260', '1', 'United', '21', 'United Healthcare – Select');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('261', '1', 'United', '21', 'United Healthcare - Select Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('262', '1', 'United', '21', 'United Healthcare – Select Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('263', '1', 'United', '21', 'United Healthcare AARP Medicare Advantage Walgreens (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('264', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage Choice (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('265', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage from UHC IL-0001');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('266', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage from UHC IL-0002');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('267', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage from UHC IL-0003');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('268', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage from UHC IL-0004');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('269', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage from UHC IL-001P');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('270', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage Patriot (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('271', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage Patriot No Rx IL-MA01');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('272', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage Plan 1 (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('273', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage Plan 2 (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('274', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage Walgreens (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('275', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage Walgreens from UHC IL-0005');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('276', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage Walgreens from UHC IL-0006');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('277', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage Walgreens (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('278', '1', 'United', '21', 'United Healthcare Affiliates - Participate through UHC PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('279', '1', 'United', '21', 'United Healthcare Affiliates – Participate through UHC PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('280', '1', 'United', '21', 'United HealthCare Chronic Complete Assure (PPO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('281', '1', 'United', '21', 'United HealthCare Medicare Advantage PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('282', '1', 'United', '21', 'United HealthCare Medicare Complete Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('283', '1', 'United', '21', 'United HealthCare Medicare Complete Access ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('284', '1', 'United', '21', 'United HealthCare Nursing Home Plan IL-F002');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('285', '1', 'United', '21', 'United HealthCare UHC Complete Care IL-001A');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('286', '1', 'United', '21', 'United HealthCare AARP® Medicare Advantage Walgreens (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('287', '1', 'United', '21', 'UnitedHealthcare Nursing Home Plan 1 (HMO/POS-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('288', '1', 'United', '21', 'UnitedHealthcare Nursing Home Plan 2 (PPO-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('289', '3', 'VA', '19', 'Veteran Affairs Community Care Network administered by Optum');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('290', '1', 'WellCare', '26', 'WellCare Edge (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('291', '1', 'WellCare', '26', 'WellCare Essential (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('292', '1', 'WellCare', '26', 'WellCare Essential (HMO-POS)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('293', '1', 'WellCare', '26', 'WellCare Exclusive (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('294', '1', 'WellCare', '26', 'WellCare Exclusive (HMO-POS)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('295', '1', 'Medicaid', '18', 'YouthCare IL');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('296', '1', 'Zing', '23', 'Zing Choice (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('297', '1', 'Zing', '23', 'Zing Choice Diabetes & Heart Complete (PPO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('298', '1', 'Zing', '23', 'Zing Complete Open Choice (PPO D-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('299', '1', 'Zing', '23', 'Zing Complete Plus (HMO D-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('300', '1', 'Zing', '23', 'Zing Complete Select (HMO D-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('301', '1', 'Zing', '23', 'Zing Elite Diabetes & Heart (HMO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('302', '1', 'Zing', '23', 'Zing Elite Select (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('303', '1', 'Zing', '23', 'Zing ESRD Select (HMO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('304', '1', 'Zing', '23', 'Zing Essential Wellness Diabetes & Heart (HMO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('305', '1', 'Zing', '23', 'Zing Health');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('306', '1', 'Zing', '23', 'Zing Open Choice (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('307', '1', 'Zing', '23', 'Zing Open Choice Diabetes & Heart (PPO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('308', '1', 'Zing', '23', 'Zing Select Care (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('309', '1', 'Zing', '23', 'Zing Select Diabetes & Heart (HMO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES ('310', '1', 'Zing', '23', 'Zing Select Diabetes & Heart Complete (HMO C-SNP)');
=======
USE ChargeMasterDB;
GO


-- Create the new table
CREATE TABLE InsurancePlans (
    PlanID INT NOT NULL,
    InsuranceTypeID INT,
    CarrierName NVARCHAR(255),
    CarrierID INT,
    PlanName NVARCHAR(255),
    CONSTRAINT PK_InsurancePlans PRIMARY KEY (PlanID),
    CONSTRAINT FK_InsurancePlans_InsuranceTypes FOREIGN KEY (InsuranceTypeID)
        REFERENCES InsuranceTypes (InsuranceTypeID)
);



INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (1, 1, 'Aetna', 1, 'Aetna - HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (2, 1, 'Aetna', 1, 'Aetna - Open Access HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (3, 1, 'Aetna', 1, 'Aetna - PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (4, 1, 'Aetna', 1, 'Aetna Choice POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (5, 1, 'Aetna', 1, 'Aetna Choice POS II');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (6, 1, 'Aetna', 1, 'Aetna Elect Choice');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (7, 1, 'Aetna', 1, 'Aetna EPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (8, 1, 'Aetna', 1, 'Aetna Health Network Only');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (9, 1, 'Aetna', 1, 'Aetna Health Network Option');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (10, 1, 'Aetna', 1, 'Aetna HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (11, 1, 'Aetna', 1, 'Aetna Illinois Preferred Plan');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (12, 1, 'Aetna', 1, 'Aetna Managed Choice POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (13, 1, 'Aetna', 1, 'Aetna NAP');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (14, 1, 'Aetna', 1, 'Aetna Open Access Elect Choice');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (15, 1, 'Aetna', 1, 'Aetna Open Access HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (16, 1, 'Aetna', 1, 'Aetna Open Access Managed Choice');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (17, 1, 'Aetna', 1, 'Aetna Open Choice PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (18, 1, 'Aetna', 1, 'Aetna Performance Network');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (19, 1, 'Aetna', 1, 'Aetna Performance Network (Tier 2)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (20, 1, 'Aetna', 1, 'Aetna Premier Care Network');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (21, 1, 'Aetna', 1, 'Aetna Premier Care Network Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (22, 1, 'Aetna', 1, 'Aetna Prime HMO-POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (23, 1, 'Aetna', 1, 'Aetna QPOS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (24, 1, 'Aetna', 1, 'Aetna Savings Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (25, 1, 'Aetna', 1, 'Aetna Savings Plus (Tier 2)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (26, 1, 'Aetna', 1, 'Aetna Select');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (27, 1, 'Aetna', 1, 'Aetna Student Health');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (28, 1, 'Aetna', 1, 'Aetna Traditional Choice');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (29, 1, 'Aetna', 1, 'Aetna Voluntary Group Medical Plan (Indemnity Plan)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (30, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Bronze PPO 201');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (31, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Bronze PPO 202');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (32, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Bronze PPO 601 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (33, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Bronze PPO 701 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (34, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Bronze PPO 708');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (35, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Bronze PPO 302');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (36, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Bronze PPO 502');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (37, 3, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Bronze PPO 601');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (38, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Bronze PPO 701');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (39, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Bronze PPO 705');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (40, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Gold PPO 204 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (41, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Gold PPO 707');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (42, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Gold PPO 204');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (43, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Silver PPO 203');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (44, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Silver PPO 303');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (45, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Silver PPO 706');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (46, 1, 'Blue Cross Blue Shield', 3, 'Blue Choice Preferred Silver PPO 801 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (47, 1, 'Blue Cross Blue Shield', 3, 'Blue Cross Blue Shield - Blue Advantage HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (48, 1, 'Blue Cross Blue Shield', 3, 'Blue Cross Blue Shield - Blue Choice Options');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (49, 1, 'Blue Cross Blue Shield', 3, 'Blue Cross Blue Shield - Blue Choice Options (Tier 1)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (50, 1, 'Blue Cross Blue Shield', 3, 'Blue Cross Blue Shield - Blue Choice PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (51, 1, 'Blue Cross Blue Shield', 3, 'Blue Cross Blue Shield - HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (52, 1, 'Blue Cross Blue Shield', 3, 'Blue Cross Blue Shield - HMOI');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (53, 1, 'Blue Cross Blue Shield', 3, 'Blue Cross Blue Shield - PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (54, 1, 'Blue Cross Blue Shield', 3, 'Blue Precision Bronze HMO 205');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (55, 1, 'Blue Cross Blue Shield', 3, 'Blue Precision Bronze HMO 701 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (56, 1, 'Blue Cross Blue Shield', 3, 'Blue Precision Bronze HMO 708');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (57, 1, 'Blue Cross Blue Shield', 3, 'Blue Precision Gold HMO 207');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (58, 1, 'Blue Cross Blue Shield', 3, 'Blue Precision Gold HMO 703 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (59, 1, 'Blue Cross Blue Shield', 3, 'Blue Precision Gold HMO 707');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (60, 1, 'Blue Cross Blue Shield', 3, 'Blue Precision Silver HMO 206');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (61, 1, 'Blue Cross Blue Shield', 3, 'Blue Precision Silver HMO 306');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (62, 1, 'Blue Cross Blue Shield', 3, 'Blue Precision Silver HMO 704 - Rx Copays');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (63, 1, 'Blue Cross Blue Shield', 3, 'Blue Precision Silver HMO 706');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (64, 2, 'CHAMPUS', 16, 'CHAMPUS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (65, 1, 'Cigna', 4, 'Cigna - Choice Fund Open Access Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (66, 1, 'Cigna', 4, 'Cigna - ChoiceCare PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (67, 1, 'Cigna', 4, 'Cigna - EPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (68, 1, 'Cigna', 4, 'Cigna - Global Health Benefits');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (69, 1, 'Cigna', 4, 'Cigna - GWH POS Open Access Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (70, 1, 'Cigna', 4, 'Cigna - HMO (or POS)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (71, 1, 'Cigna', 4, 'Cigna - HMO (or POS) Open Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (72, 1, 'Cigna', 4, 'Cigna - Local Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (73, 1, 'Cigna', 4, 'Cigna - Network Open Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (74, 1, 'Cigna', 4, 'Cigna - Network POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (75, 1, 'Cigna', 4, 'Cigna - One Health HMO eff 4/1/19');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (76, 1, 'Cigna', 4, 'Cigna - Open Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (77, 1, 'Cigna', 4, 'Cigna - Open Access Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (78, 1, 'Cigna', 4, 'Cigna - POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (79, 1, 'Cigna', 4, 'Cigna - PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (80, 1, 'Cigna', 4, 'Cigna - Shared Administration PPO and OAP');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (81, 1, 'Cigna', 4, 'Cigna Courage Medicare (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (82, 1, 'Cigna', 4, 'Cigna Plus Bronze CMS Standard');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (83, 1, 'Cigna', 4, 'Cigna Plus Gold CMS Standard - Rx Copay');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (84, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 0-2*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (85, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 0-3*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (86, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 0-4A*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (87, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 0-4B*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (88, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 0A*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (89, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 0B*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (90, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 100-4 Rx Copay*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (91, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 1900 Enhanced Diabetes Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (92, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 2000-3*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (93, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 2500-2 Rx Copay*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (94, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 3000 Rx Copay*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (95, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 3000-2 Enhanced Diabetes Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (96, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 350-3 Rx Copay*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (97, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 3550-2 Enhanced Asthma COPD Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (98, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 3800 Enhanced Diabetes Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (99, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 3800-2*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (100, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 40-4 Enhanced Diabetes Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (101, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 4200 Enhanced Asthma COPD Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (102, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 5000 Rx Copay*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (103, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 50-4 Enhanced Asthma COPD Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (104, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 6000*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (105, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 600-3 Enhanced Diabetes Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (106, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 6150-2*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (107, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 650-4*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (108, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 6800 Enhanced Diabetes Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (109, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 700-3*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (110, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 750 Rx Copay*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (111, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 750-3 Enhanced Asthma COPD Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (112, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine 8000*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (113, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine Diabetes 7600 Enhanced Asthma COPD Care*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (114, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine HSA 7050*');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (115, 1, 'Cigna', 4, 'Cigna Plus Northwestern Medicine will not be available for residents of Cook County. However, residents of DuPage, Kane, Lake and McHenry counties will still have coverage in Cook County if they receive care at Northwestern Memorial Hospital.');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (116, 1, 'Cigna', 4, 'Cigna Plus Silver CMS Standard');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (117, 1, 'Cigna', 4, 'Cigna Plus Silver-2 CMS Standard');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (118, 1, 'Cigna', 4, 'Cigna Plus Silver-3 CMS Standard');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (119, 1, 'Cigna', 4, 'Cigna Plus Silver-4 CMS Standard');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (120, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (121, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine 1000**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (122, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine 1250 - Northwestern Medicine Only**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (123, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine 2000 *');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (124, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine 2000 *');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (125, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine 3000**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (126, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine 3500 Diabetes Care**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (127, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine 4400 *');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (128, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine 4400 *');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (129, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine 5000**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (130, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine 6000**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (131, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine 7000**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (132, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine 750**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (133, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine 7500**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (134, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine 8500**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (135, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine 8700**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (136, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine Asthma/COPD 4200**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (137, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine Bronze 5000 Indiv Med Deductible - Rx Copay');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (138, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine Diabetes 6800**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (139, 1, 'Cigna', 4, 'Cigna Plus With Northwestern Medicine Plan 0**');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (140, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine Silver 3000 Indiv Med Deductible - Rx Copay');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (141, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine Silver 5000 Indiv Med Deductible');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (142, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine Silver-2 2500 Indiv Med Deductible - Rx Copay');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (143, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine Silver-2 3800 Indiv Med Deductible');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (144, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine Silver-3 350 Indiv Med Deductible - Rx Copay');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (145, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine Silver-3 700 Indiv Med Deductible');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (146, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine Silver-4 0 Indiv Med Deductible');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (147, 1, 'Cigna', 4, 'Cigna Plus with Northwestern Medicine Silver-4 100 Indiv Med Deductible - Rx Copay');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (148, 1, 'Cigna', 4, 'Cigna Preferred Medicare (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (149, 1, 'Cigna', 4, 'Cigna Simple Choice 0-4C');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (150, 1, 'Cigna', 4, 'Cigna Simple Choice 2000');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (151, 1, 'Cigna', 4, 'Cigna Simple Choice 5700-2');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (152, 1, 'Cigna', 4, 'Cigna Simple Choice 5800');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (153, 1, 'Cigna', 4, 'Cigna Simple Choice 7500');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (154, 1, 'Cigna', 4, 'Cigna Simple Choice 9100');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (155, 1, 'Cigna', 4, 'Cigna True Choice Courage Medicare (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (156, 1, 'Cigna', 4, 'Cigna True Choice Medicare (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (157, 1, 'Cigna', 4, 'Cigna True Choice Plus Medicare (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (158, 1, 'Cigna', 4, 'Cigna True Choice Savings Medicare (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (159, 1, 'Cigna', 4, 'Cigna - Local Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (160, 4, 'Medicaid', 18, 'CountyCare Medicaid');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (161, 1, 'Health Alliance', 9, 'Health Alliance');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (162, 1, 'Health Alliance', 9, 'Health Alliance Marketplace Plans HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (163, 1, 'Health Alliance', 9, 'Health Alliance ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (164, 1, 'HFN', 10, 'HFN - EPO (HFN20)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (165, 1, 'HFN', 10, 'HFN - Platinum');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (166, 1, 'HFN', 10, 'HFN - PPO (HFN10)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (167, 1, 'HFN', 10, 'HFN - Workers Compensation Program/Network');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (168, 1, 'Humana', 11, 'Humana - Choice Care PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (169, 1, 'Humana', 11, 'Humana - Choice POS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (170, 1, 'Humana', 11, 'Humana - ChoiceCare PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (171, 1, 'Humana', 11, 'Humana - EPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (172, 1, 'Humana', 11, 'Humana - HMO Premier');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (173, 1, 'Humana', 11, 'Humana - HMO Select');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (174, 1, 'Humana', 11, 'Humana - Illinois Platinum HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (175, 1, 'Humana', 11, 'Humana - National Preferred POS - Open Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (176, 1, 'Humana', 11, 'Humana - PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (177, 1, 'Humana', 11, 'Humana - Preferred PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (178, 1, 'Humana', 11, 'Humana Behavioral Health');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (179, 1, 'Humana', 11, 'Humana HMO Gold Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (180, 1, 'Humana', 11, 'Humana Honor PPO (Veterans Plan)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (181, 1, 'Humana', 11, 'Humana PFFS');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (182, 1, 'Humana', 11, 'Humana PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (183, 4, 'Medicaid', 18, 'IDPA Medicaid');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (184, 5, 'Medicare', 17, 'Medicare');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (185, 4, 'Medicaid', 18, 'Meridian Medicaid');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (186, 9, 'Meridian', 25, 'Meridian Complete');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (187, 2, 'Tricare East', 20, 'TriCare East Administered by Humana Military');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (188, 1, 'United', 21, 'United Behavioral Health - Optum');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (189, 1, 'United', 21, 'United Healthcare - All Savers');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (190, 1, 'United', 21, 'United Healthcare - Choice');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (191, 1, 'United', 21, 'United Healthcare - Choice Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (192, 1, 'United', 21, 'United Healthcare - Core');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (193, 1, 'United', 21, 'United Healthcare - HMO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (194, 1, 'United', 21, 'United Healthcare - HMO Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (195, 1, 'United', 21, 'United Healthcare - HMO ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (196, 1, 'United', 21, 'United Healthcare - Navigate');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (197, 1, 'United', 21, 'United Healthcare - Open Access ');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (198, 1, 'United', 21, 'United Healthcare - Options PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (199, 1, 'United', 21, 'United Healthcare - Select');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (200, 1, 'United', 21, 'United Healthcare - Select Plus');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (201, 1, 'United', 21, 'United Healthcare AARP Medicare Advantage Walgreens (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (202, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage Choice (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (203, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage from UHC IL-0001');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (204, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage from UHC IL-0002');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (205, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage from UHC IL-0003');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (206, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage from UHC IL-0004');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (207, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage from UHC IL-001P');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (208, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage Patriot (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (209, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage Patriot No Rx IL-MA01');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (210, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage Plan 1 (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (211, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage Plan 2 (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (212, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage Walgreens (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (213, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage Walgreens from UHC IL-0005');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (214, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage Walgreens from UHC IL-0006');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (215, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage Walgreens (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (216, 1, 'United', 21, 'United Healthcare Affiliates - Participate through UHC PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (217, 1, 'United', 21, 'United HealthCare Chronic Complete Assure (PPO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (218, 1, 'United', 21, 'United HealthCare Medicare Advantage PPO');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (219, 1, 'United', 21, 'United HealthCare Medicare Complete Access');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (220, 1, 'United', 21, 'United HealthCare Nursing Home Plan IL-F002');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (221, 1, 'United', 21, 'United HealthCare UHC Complete Care IL-001A');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (222, 1, 'United', 21, 'United HealthCare AARP® Medicare Advantage Walgreens (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (223, 1, 'United', 21, 'UnitedHealthcare Nursing Home Plan 1 (HMO/POS-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (224, 1, 'United', 21, 'UnitedHealthcare Nursing Home Plan 2 (PPO-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (225, 3, 'VA', 19, 'Veteran Affairs Community Care Network administered by Optum');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (226, 1, 'WellCare', 26, 'WellCare Edge (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (227, 1, 'WellCare', 26, 'WellCare Essential (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (228, 1, 'WellCare', 26, 'WellCare Essential (HMO-POS)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (229, 1, 'WellCare', 26, 'WellCare Exclusive (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (230, 1, 'WellCare', 26, 'WellCare Exclusive (HMO-POS)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (231, 1, 'Medicaid', 18, 'YouthCare IL');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (232, 1, 'Zing', 23, 'Zing Choice (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (233, 1, 'Zing', 23, 'Zing Choice Diabetes & Heart Complete (PPO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (234, 1, 'Zing', 23, 'Zing Complete Open Choice (PPO D-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (235, 1, 'Zing', 23, 'Zing Complete Plus (HMO D-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (236, 1, 'Zing', 23, 'Zing Complete Select (HMO D-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (237, 1, 'Zing', 23, 'Zing Elite Diabetes & Heart (HMO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (238, 1, 'Zing', 23, 'Zing Elite Select (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (239, 1, 'Zing', 23, 'Zing ESRD Select (HMO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (240, 1, 'Zing', 23, 'Zing Essential Wellness Diabetes & Heart (HMO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (241, 1, 'Zing', 23, 'Zing Health');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (242, 1, 'Zing', 23, 'Zing Open Choice (PPO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (243, 1, 'Zing', 23, 'Zing Open Choice Diabetes & Heart (PPO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (244, 1, 'Zing', 23, 'Zing Select Care (HMO)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (245, 1, 'Zing', 23, 'Zing Select Diabetes & Heart (HMO C-SNP)');
INSERT INTO InsurancePlans (PlanID, InsuranceTypeID, CarrierName, CarrierID, PlanName) VALUES (246, 1, 'Zing', 23, 'Zing Select Diabetes & Heart Complete (HMO C-SNP)');
>>>>>>> de5cae1c6fe4403fcd0312bb2166b8e40d1bc83b
