INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'MultiPlan-PHCS', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'ComPsych', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Coventry', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Curaechoice', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Global Excel', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Health Alliance', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Health Alliance', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'HFN', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'HFN', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'HFN', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Imagine Health', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'MultiPlan-PHCS', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'The Alliance', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'Optum', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 2, 'CHAMPUS', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 2, 'Medicare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 2, 'Medicaid', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 2, 'VA', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 2, 'Tricare East', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Aetna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Cigna', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Health Alliance', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United HealthCare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'United', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 7, 'Zing', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 8, 'Zing', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 8, 'Zing', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 8, 'Zing', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 6, 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 6, 'CountyCare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, EligibilityYear) VALUES (4, 27, 6, 'Meridian', 2023);
