USE ChargeMasterDB;
GO

CREATE TABLE dbo.Carriers (
    CarrierID INT PRIMARY KEY IDENTITY(1,1), -- Auto-incrementing primary key
    CarrierName VARCHAR(255) NOT NULL
);

CREATE TABLE dbo.InsurancePlans (
    PlanID INT PRIMARY KEY IDENTITY(1,1), -- Auto-incrementing primary key
    CarrierID INT NOT NULL,
    InsuranceType VARCHAR(255) NOT NULL,
    PlanName VARCHAR(255) NOT NULL,
    FOREIGN KEY (CarrierID) REFERENCES dbo.Carriers(CarrierID) -- Foreign key to the Carriers table
);



CREATE TABLE dbo.InsuranceTypes (
    InsuranceTypeID INT PRIMARY KEY,
    InsuranceType NVARCHAR(255) NOT NULL
);



ALTER TABLE dbo.InsurancePlans
ADD InsuranceTypeID INT;

ALTER TABLE dbo.InsurancePlans
ADD CONSTRAINT FK_InsurancePlans_InsuranceTypes
FOREIGN KEY (InsuranceTypeID) REFERENCES dbo.InsuranceTypes(InsuranceTypeID);



INSERT INTO dbo.InsuranceTypes (InsuranceTypeID, InsuranceType) VALUES (1, 'Commercial');
INSERT INTO dbo.InsuranceTypes (InsuranceTypeID, InsuranceType) VALUES (2, 'Government');
INSERT INTO dbo.InsuranceTypes (InsuranceTypeID, InsuranceType) VALUES (3, 'Exchange');
INSERT INTO dbo.InsuranceTypes (InsuranceTypeID, InsuranceType) VALUES (4, 'Medicaid');
INSERT INTO dbo.InsuranceTypes (InsuranceTypeID, InsuranceType) VALUES (5, 'Medicare');
INSERT INTO dbo.InsuranceTypes (InsuranceTypeID, InsuranceType) VALUES (7, 'Managed Medicaid');
INSERT INTO dbo.InsuranceTypes (InsuranceTypeID, InsuranceType) VALUES (8, 'Medicare Advantage');
INSERT INTO dbo.InsuranceTypes (InsuranceTypeID, InsuranceType) VALUES (9, 'Medicare/Medicaid Initiative (MMAI)');




INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (1, 'Aetna');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (2, 'MultiPlan-PHCS');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (3, 'Blue Cross Blue Shield');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (4, 'Cigna');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (5, 'ComPsych');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (6, 'Coventry');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (7, 'Curaechoice');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (8, 'Global Excel');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (9, 'Health Alliance');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (10, 'HFN');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (11, 'Humana');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (12, 'Imagine Health');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (13, 'The Alliance');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (14, 'Optum');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (15, 'United Healthcare');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (16, 'CHAMPUS');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (17, 'Medicare');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (18, 'Medicaid');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (19, 'VA');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (20, 'Tricare East');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (21, 'United');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (22, 'United HealthCare');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (23, 'Zing');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (24, 'CountyCare');
INSERT INTO dbo.Carriers (CarrierID, CarrierName) VALUES (25, 'Meridian');
Use ChargeMasterDB;
go

INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Choice POS ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Choice POS II ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Elect Choice ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna EPO ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Health Network Only ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Health Network Option ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna HMO ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Illinois Preferred Plan', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Managed Choice POS ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna NAP ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Open Access Elect Choice ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Open Access HMO ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Open Access Managed Choice ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Open Choice PPO ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Performance Network ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Premier Care Network ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Premier Care Network Plus ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna QPOS ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Savings Plus ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Select ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Student Health ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Traditional Choice ', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Voluntary Group Medical Plan (Indemnity Plan)', 1, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('BeechStreet (PHCS)', 2, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Cross Blue Shield - Blue Advantage HMOÂ (See IPA/Referral)', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Cross Blue Shield - Blue Choice PPO ', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Cross Blue Shield - Blue Choice Options (Tier 1)', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Cross Blue Shield - HMOI (See IPA/Referral)', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Cross Blue Shield - PPO', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Gold PPO 204', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Gold PPO 707', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Gold HMO 207', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Gold HMO 703 - Rx Copays', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Gold HMO 707', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Silver PPO 303', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Silver PPO 203', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Silver PPO 706', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMO 206', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMO 306', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMO 704 - Rx Copays', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMO 706', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 302', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 502', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 201', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 202', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 601', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 701', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 705', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 708', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Bronze HMO 205', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Bronze HMO 701 - Rx Copays', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Bronze HMO 708', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Gold PPOSM 204 - Rx Copays', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Gold PPOSM 707', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Gold HMOSM 207', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Gold HMOSM 703 - Rx Copays', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Gold HMOSM 707', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Silver PPOSM 203', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Silver PPOSM 303', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Silver PPOSM 706', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Silver PPOSM 801 - Rx Copays', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMOSM 206', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMOSM 306', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMOSM 704 - Rx Copays', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMOSM 706', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPOSM 201', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPOSM 202', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPOSM 601 - Rx Copays', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPOSM 701 - Rx Copays', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPOSM 708', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Bronze HMOSM 205', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Bronze HMOSM 701 - Rx Copays', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Bronze HMOSM 708', 3, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - Open Access ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - Open Access Plus ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - Choice Fund Open Access Plus ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - ChoiceCare PPO ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - EPO ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - Global Health Benefits ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - GWH POS Open Access Plus ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - HMO (or POS) ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - HMO (or POS) Open Access ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - Local Plus ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - Network Open Access ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - Network POS ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - One Health HMO eff 4/1/19 ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus with Northwestern Medicine 4400', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus with Northwestern Medicine 2000', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - POS ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - PPO ', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna - Shared Administration PPO and OAP', 4, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('ComPsych â€” Behavioral Health/Substance Abuse Network', 5, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Coventry Health Care - First Health HMO, PPO and POS', 6, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Curaechoice', 7, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Global Excel - PPO', 8, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Health Alliance - PPO', 9, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Health Alliance - HMO', 9, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('HFN - EPO (HFN20)', 10, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('HFN - PPO (HFN10)', 10, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('HFN - Workers'' Compensation Program/Network', 10, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana - Choice POS ', 11, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana - ChoiceCare PPO ', 11, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana - EPO ', 11, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana - HMO Premier ', 11, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana - HMO Select ', 11, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana - Illinois Platinum HMO ', 11, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana - National Preferred POS - Open Access ', 11, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana - PPO ', 11, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana - Preferred PPO', 11, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Imagine Health', 12, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('MultiPlan/PHCS', 2, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('The Alliance', 13, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Behavioral Health', 14, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Healthcare - All Savers ', 15, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Healthcare - Choice ', 15, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Healthcare - Choice Plus ', 15, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Healthcare - Core ', 15, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Healthcare - HMO(See IPA/Referral)', 15, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Healthcare - HMO Plus ', 15, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Healthcare - Navigate ', 15, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Healthcare - Open Access(See IPA/Referral)', 15, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Healthcare - Options PPO ', 15, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Healthcare - Select Plus ', 15, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Healthcare - Select ', 15, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Healthcare Affiliates - Participate through UHC PPO', 15, 'Commercial', 1);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 201', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 202', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 601', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 701', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 705', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPO 708', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Bronze HMO 205', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Bronze HMO 701 - Rx Copays', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Bronze HMO 708', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 0A*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 5000 Rx Copay*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine HSA 7050*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 6800 Enhanced Diabetes Care*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine Diabetes 7600 Enhanced Asthma COPD Care*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Simple Choice 9100', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Simple Choice 7500', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Silver PPO 203', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Silver PPO 706', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMO 206', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMO 704 - Rx Copays', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMO 706', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 6000*Â ', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 3800-2*Â ', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 700-3*Â ', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 0-4A*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 0B*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 0-2*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 0-3*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 0-4B*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 3000 Rx Copay*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 2500-2 Rx Copay*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 350-3 Rx Copay*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 100-4 Rx Copay*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 8000*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 6150-2*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 2000-3*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 650-4*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 3800 Enhanced Diabetes Care*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 3000-2 Enhanced Diabetes Care*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 600-3 Enhanced Diabetes Care*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 40-4 Enhanced Diabetes Care*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 4200 Enhanced Asthma COPD Care*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 3550-2 Enhanced Asthma COPD Care*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 750-3 Enhanced Asthma COPD Care*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 50-4 Enhanced Asthma COPD Care*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Simple Choice 5800', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Simple Choice 5700-2', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Simple Choice 0-4CÂ ', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Gold PPO 204', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Gold PPO 707', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Gold HMO 207', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Gold HMO 703 - RX Copays', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Gold HMO 707', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 750 Rx Copay*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Simple Choice 2000', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Northwestern Medicine 1900 Enhanced Diabetes Care*', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPOSM 201', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPOSM 202', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPOSM 601 - Rx Copays', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPOSM 701 - Rx Copays', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Bronze PPOSM 708', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Bronze HMOSM 205', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Bronze HMOSM 701 - Rx Copays', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Bronze HMOSM 708', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Bronze CMS Standard', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus with Northwestern Medicine Bronze 5000 Indiv Med Deductible - Rx Copay', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Silver PPOSM 203', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Silver PPOSM 706', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Silver PPOSM 801 - Rx Copays', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMOSM 206', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMOSM 704 - Rx Copays', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Silver HMOSM 706', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Silver CMS Standard', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Silver-2 CMS Standard', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Silver-3 CMS Standard', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Silver-4 CMS Standard', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus with Northwestern Medicine Silver 3000 Indiv Med Deductible - Rx Copay', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus with Northwestern Medicine Silver-2 2500 Indiv Med Deductible - Rx Copay', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus with Northwestern Medicine Silver-3 350 Indiv Med Deductible - Rx Copay', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus with Northwestern Medicine Silver-4 100 Indiv Med Deductible - Rx Copay', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus with Northwestern Medicine Silver 5000 Indiv Med Deductible', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus with Northwestern Medicine Silver-2 3800 Indiv Med Deductible', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus with Northwestern Medicine Silver-3 700 Indiv Med Deductible', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus with Northwestern Medicine Silver-4 0 Indiv Med Deductible', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Gold PPOSM 204 - Rx Copays', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Choice Preferred Gold PPOSM 707', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Gold HMOSM 207', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Gold HMOSM 703 - Rx Copays', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Precision Gold HMOSM 707', 3, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Plus Gold CMS Standard - Rx Copay', 4, 'Exchange', 3);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('CHAMPUS', 16, 'Government', 2);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Medicare ', 17, 'Government', 2);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Medicaid', 18, 'Government', 2);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Veteran''s Affairs Community Care Netwwork by Optum', 19, 'Government', 2);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Tricare East Administered by Humana Military', 20, 'Government', 2);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna - HMOÂ ', 1, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna - PPOÂ ', 1, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna - Open Access HMO', 1, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Aetna Prime HMO-POS', 1, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Cross Blue Shield - PPOÂ Â ', 3, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Cross Blue Shield - HMOÂ ', 3, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna True Choice Plus Medicare (PPO) (Out-of-Network as of January 1, 2024)', 4, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Preferred Medicare (HMO) (Out-of-Network as of January 1, 2024)', 4, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna True Choice Medicare (PPO) (Out-of-Network as of January 1, 2024)', 4, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna True Choice Savings Medicare (PPO) (Out-of-Network as of January 1, 2024)', 4, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna Courage Medicare (HMO) (Out-of-Network as of January 1, 2024)', 4, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Cigna True Choice Courage Medicare (PPO) (Out-of-Network as of January 1, 2024)', 4, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Health AllianceÂ  (See IPA/Referral)', 9, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana HMO Gold Plus', 11, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana PFFS', 11, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana PPO', 11, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana Honor PPO (Veterans Plan)', 11, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare Chronic Complete Assure (PPO C-SNP)', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare Medicare Complete Access (See IPA/Referral)', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare Medicare Advantage PPOÂ ', 22, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare AARPÂ® Medicare Advantage 1 (HMO)', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare AARPÂ® Medicare Advantage 2 (HMO)', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare AARPÂ® Medicare Advantage Choice (PPO)', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United Healthcare AARP Medicare Advantage Walgreens (PPO)', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare AARPÂ® Medicare Advantage Patriot (PPO)', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare AARPÂ® Medicare Advantage from UHC IL-0001Â ', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare AARPÂ® Medicare Advantage from UHC IL-0002Â ', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare AARPÂ® Medicare Advantage from UHC IL-0004Â ', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare AARPÂ® Medicare Advantage Walgreens from UHC IL-0005Â ', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare AARPÂ® Medicare Advantage from UHC IL-0003Â ', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare AARPÂ® Medicare Advantage Walgreens from UHC IL-0006Â ', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare UHC Complete Care IL-001AÂ ', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('United HealthCare AARPÂ® Medicare Advantage Patriot No Rx IL-MA01Â ', 21, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Choice (HMO) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Choice Diabetes & Heart Complete (PPO C-SNP) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Complete Select (HMO D-SNP) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Complete Open Choice (PPO D-SNP) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Complete Plus (HMO D-SNP) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Elite Diabetes & Heart (HMO C-SNP) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Elite Select (HMO) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('ESRD Select (HMO C-SNP) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Essential Wellness Diabetes & Heart (HMO C-SNP) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Open Choice (PPO) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Open Choice Diabetes & Heart (PPO C-SNP) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Select Care (HMO) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Select Diabetes & Heart (HMO C-SNP) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Select Diabetes & Heart Complete (HMO C-SNP) ', 23, 'Managed Medicaid', 7);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Cross Blue Shield', 23, 'Medicare Advantage', 8);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Humana', 23, 'Medicare Advantage', 8);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Health ', 23, 'Medicare Advantage', 8);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Blue Cross Blue Shield', 3, 'Other', 6);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('CountyCare', 24, 'Other', 6);
INSERT INTO dbo.InsurancePlans (PlanName, CarrierID, InsuranceType, InsuranceTypeID) VALUES ('Meridian', 25, 'Other', 6);


CREATE TABLE dbo.Elig_Northwestern (
  EligibilityID INT IDENTITY(1,1) PRIMARY KEY,
  SystemID INT NOT NULL,
  LocationID INT FOREIGN KEY REFERENCES dbo.HospitalLocation(LocationID),
  InsuranceTypeID INT FOREIGN KEY REFERENCES dbo.InsuranceTypes(InsuranceTypeID),
  Carrier VARCHAR(255) NOT NULL,
  InNetwork BIT NOT NULL DEFAULT 1, -- Assuming InNetwork should always be 1
  EligibilityYear INT NOT NULL
);



INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Choice POS ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Choice POS II ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Elect Choice ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna EPO ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Health Network Only ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Health Network Option ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna HMO ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Illinois Preferred Plan', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Managed Choice POS ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna NAP ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Open Access Elect Choice ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Open Access HMO ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Open Access Managed Choice ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Open Choice PPO ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Performance Network ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Premier Care Network ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Premier Care Network Plus ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna QPOS ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Savings Plus ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Select ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Student Health ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Traditional Choice ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Aetna', 'Aetna Voluntary Group Medical Plan (Indemnity Plan)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'MultiPlan-PHCS', 'BeechStreet (PHCS)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Cross Blue Shield - Blue Advantage HMO�(See IPA/Referral)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Cross Blue Shield - Blue Choice PPO ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Cross Blue Shield - Blue Choice Options (Tier 1)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Cross Blue Shield - HMOI (See IPA/Referral)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Cross Blue Shield - PPO', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Gold PPO 204', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Gold PPO 707', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Gold HMO 207', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Gold HMO 703 - Rx Copays', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Gold HMO 707', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Silver PPO 303', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Silver PPO 203', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Silver PPO 706', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Silver HMO 206', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Silver HMO 306', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Silver HMO 704 - Rx Copays', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Silver HMO 706', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 302', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 502', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 201', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 202', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 601', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 701', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 705', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 708', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Bronze HMO 205', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Bronze HMO 701 - Rx Copays', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Bronze HMO 708', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Gold PPOSM 204 - Rx Copays', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Gold PPOSM 707', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Gold HMOSM 207', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Gold HMOSM 703 - Rx Copays', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Gold HMOSM 707', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Silver PPOSM 203', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Silver PPOSM 303', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Silver PPOSM 706', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Silver PPOSM 801 - Rx Copays', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Silver HMOSM 206', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Silver HMOSM 306', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Silver HMOSM 704 - Rx Copays', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Silver HMOSM 706', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPOSM 201', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPOSM 202', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPOSM 601 - Rx Copays', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPOSM 701 - Rx Copays', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPOSM 708', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Bronze HMOSM 205', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Bronze HMOSM 701 - Rx Copays', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Blue Cross Blue Shield', 'Blue Precision Bronze HMOSM 708', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - Open Access ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - Open Access Plus ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - Choice Fund Open Access Plus ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - ChoiceCare PPO ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - EPO ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - Global Health Benefits ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - GWH POS Open Access Plus ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - HMO (or POS) ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - HMO (or POS) Open Access ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - Local Plus ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - Network Open Access ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - Network POS ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - One Health HMO eff 4/1/19 ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna Plus with Northwestern Medicine 4400', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna Plus with Northwestern Medicine 2000', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - POS ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - PPO ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Cigna', 'Cigna - Shared Administration PPO and OAP', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'ComPsych', 'ComPsych � Behavioral Health/Substance Abuse Network', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Coventry', 'Coventry Health Care - First Health HMO, PPO and POS', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Curaechoice', 'Curaechoice', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Global Excel', 'Global Excel - PPO', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Health Alliance', 'Health Alliance - PPO', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Health Alliance', 'Health Alliance - HMO', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'HFN', 'HFN - EPO (HFN20)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'HFN', 'HFN - PPO (HFN10)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'HFN', 'HFN - Workers'' Compensation Program/Network', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Humana', 'Humana - Choice POS ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Humana', 'Humana - ChoiceCare PPO ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Humana', 'Humana - EPO ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Humana', 'Humana - HMO Premier ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Humana', 'Humana - HMO Select ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Humana', 'Humana - Illinois Platinum HMO ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Humana', 'Humana - National Preferred POS - Open Access ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Humana', 'Humana - PPO ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Humana', 'Humana - Preferred PPO', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Imagine Health', 'Imagine Health', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'MultiPlan-PHCS', 'MultiPlan/PHCS', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'The Alliance', 'The Alliance', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'Optum', 'United Behavioral Health', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 'United Healthcare - All Savers ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 'United Healthcare - Choice ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 'United Healthcare - Choice Plus ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 'United Healthcare - Core ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 'United Healthcare - HMO(See IPA/Referral)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 'United Healthcare - HMO Plus ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 'United Healthcare - Navigate ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 'United Healthcare - Open Access(See IPA/Referral)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 'United Healthcare - Options PPO ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 'United Healthcare - Select Plus ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 'United Healthcare - Select ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 1, 'United Healthcare', 'United Healthcare Affiliates - Participate through UHC PPO', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 201', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 202', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 601', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 701', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 705', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPO 708', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Bronze HMO 205', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Bronze HMO 701 - Rx Copays', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Bronze HMO 708', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 0A*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 5000 Rx Copay*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine HSA 7050*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 6800 Enhanced Diabetes Care*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine Diabetes 7600 Enhanced Asthma COPD Care*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Simple Choice 9100', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Simple Choice 7500', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Silver PPO 203', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Silver PPO 706', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Silver HMO 206', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Silver HMO 704 - Rx Copays', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Silver HMO 706', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 6000*�', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 3800-2*�', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 700-3*�', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 0-4A*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 0B*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 0-2*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 0-3*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 0-4B*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 3000 Rx Copay*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 2500-2 Rx Copay*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 350-3 Rx Copay*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 100-4 Rx Copay*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 8000*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 6150-2*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 2000-3*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 650-4*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 3800 Enhanced Diabetes Care*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 3000-2 Enhanced Diabetes Care*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 600-3 Enhanced Diabetes Care*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 40-4 Enhanced Diabetes Care*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 4200 Enhanced Asthma COPD Care*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 3550-2 Enhanced Asthma COPD Care*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 750-3 Enhanced Asthma COPD Care*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 50-4 Enhanced Asthma COPD Care*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Simple Choice 5800', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Simple Choice 5700-2', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Simple Choice 0-4C�', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Gold PPO 204', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Gold PPO 707', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Gold HMO 207', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Gold HMO 703 - RX Copays', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Gold HMO 707', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 750 Rx Copay*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Simple Choice 2000', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Northwestern Medicine 1900 Enhanced Diabetes Care*', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPOSM 201', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPOSM 202', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPOSM 601 - Rx Copays', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPOSM 701 - Rx Copays', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Bronze PPOSM 708', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Bronze HMOSM 205', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Bronze HMOSM 701 - Rx Copays', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Bronze HMOSM 708', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Bronze CMS Standard', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus with Northwestern Medicine Bronze 5000 Indiv Med Deductible - Rx Copay', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Silver PPOSM 203', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Silver PPOSM 706', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Silver PPOSM 801 - Rx Copays', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Silver HMOSM 206', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Silver HMOSM 704 - Rx Copays', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Silver HMOSM 706', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Silver CMS Standard', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Silver-2 CMS Standard', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Silver-3 CMS Standard', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Silver-4 CMS Standard', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus with Northwestern Medicine Silver 3000 Indiv Med Deductible - Rx Copay', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus with Northwestern Medicine Silver-2 2500 Indiv Med Deductible - Rx Copay', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus with Northwestern Medicine Silver-3 350 Indiv Med Deductible - Rx Copay', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus with Northwestern Medicine Silver-4 100 Indiv Med Deductible - Rx Copay', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus with Northwestern Medicine Silver 5000 Indiv Med Deductible', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus with Northwestern Medicine Silver-2 3800 Indiv Med Deductible', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus with Northwestern Medicine Silver-3 700 Indiv Med Deductible', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus with Northwestern Medicine Silver-4 0 Indiv Med Deductible', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Gold PPOSM 204 - Rx Copays', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Choice Preferred Gold PPOSM 707', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Gold HMOSM 207', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Gold HMOSM 703 - Rx Copays', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Blue Cross Blue Shield', 'Blue Precision Gold HMOSM 707', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 3, 'Cigna', 'Cigna Plus Gold CMS Standard - Rx Copay', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 2, 'CHAMPUS', 'CHAMPUS', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 2, 'Medicare', 'Medicare ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 2, 'Medicaid', 'Medicaid', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 2, 'VA', 'Veteran''s Affairs Community Care Netwwork by Optum', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 2, 'Tricare East', 'Tricare East Administered by Humana Military', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Aetna', 'Aetna - HMO�', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Aetna', 'Aetna - PPO�', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Aetna', 'Aetna - Open Access HMO', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Aetna', 'Aetna Prime HMO-POS', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Blue Cross Blue Shield', 'Blue Cross Blue Shield - PPO��', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Blue Cross Blue Shield', 'Blue Cross Blue Shield - HMO�', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Cigna', 'Cigna True Choice Plus Medicare (PPO) (Out-of-Network as of January 1, 2024)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Cigna', 'Cigna Preferred Medicare (HMO) (Out-of-Network as of January 1, 2024)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Cigna', 'Cigna True Choice Medicare (PPO) (Out-of-Network as of January 1, 2024)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Cigna', 'Cigna True Choice Savings Medicare (PPO) (Out-of-Network as of January 1, 2024)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Cigna', 'Cigna Courage Medicare (HMO) (Out-of-Network as of January 1, 2024)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Cigna', 'Cigna True Choice Courage Medicare (PPO) (Out-of-Network as of January 1, 2024)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Health Alliance', 'Health Alliance� (See IPA/Referral)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Humana', 'Humana HMO Gold Plus', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Humana', 'Humana PFFS', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Humana', 'Humana PPO', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Humana', 'Humana Honor PPO (Veterans Plan)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare Chronic Complete Assure (PPO C-SNP)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare Medicare Complete Access (See IPA/Referral)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United HealthCare', 'United HealthCare Medicare Advantage PPO�', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare AARP� Medicare Advantage 1 (HMO)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare AARP� Medicare Advantage 2 (HMO)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare AARP� Medicare Advantage Choice (PPO)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United Healthcare AARP Medicare Advantage Walgreens (PPO)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare AARP� Medicare Advantage Patriot (PPO)', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare AARP� Medicare Advantage from UHC IL-0001�', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare AARP� Medicare Advantage from UHC IL-0002�', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare AARP� Medicare Advantage from UHC IL-0004�', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare AARP� Medicare Advantage Walgreens from UHC IL-0005�', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare AARP� Medicare Advantage from UHC IL-0003�', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare AARP� Medicare Advantage Walgreens from UHC IL-0006�', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare UHC Complete Care IL-001A�', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'United', 'United HealthCare AARP� Medicare Advantage Patriot No Rx IL-MA01�', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'Choice (HMO) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'Choice Diabetes & Heart Complete (PPO C-SNP) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'Complete Select (HMO D-SNP) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'Complete Open Choice (PPO D-SNP) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'Complete Plus (HMO D-SNP) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'Elite Diabetes & Heart (HMO C-SNP) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'Elite Select (HMO) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'ESRD Select (HMO C-SNP) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'Essential Wellness Diabetes & Heart (HMO C-SNP) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'Open Choice (PPO) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'Open Choice Diabetes & Heart (PPO C-SNP) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'Select Care (HMO) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'Select Diabetes & Heart (HMO C-SNP) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 7, 'Zing', 'Select Diabetes & Heart Complete (HMO C-SNP) ', 2024);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 8, 'Zing', 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 8, 'Zing', 'Humana', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 8, 'Zing', 'Health ', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 6, 'Blue Cross Blue Shield', 'Blue Cross Blue Shield', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 6, 'CountyCare', 'CountyCare', 2023);
INSERT INTO dbo.Elig_Northwestern (SystemID, LocationID, InsuranceTypeID, Carrier, PlanName, EligibilityYear) VALUES (4, 27, 6, 'Meridian', 'Meridian', 2023);
ALTER TABLE dbo.Elig_Northwestern
ADD PlanName VARCHAR(255);

TRUNCATE TABLE dbo.Elig_Northwestern;
