CREATE TABLE Charges_Advocate (
    LocationID INT FOREIGN KEY REFERENCES HospitalLocation(LocationID),
    SystemID INT FOREIGN KEY REFERENCES HospitalSystem(SystemID),
    LocationName NVARCHAR(255), -- Optional if you are using LocationID, consider removing if redundant
    BillingCode 
	VARCHAR(18) NULL,
    ServiceDescription NVARCHAR(MAX) NULL,
    RevenueCode NVARCHAR(50) NULL,
    GrossCharge DECIMAL(18, 2) NULL,
    DeidentifiedMinimumCharge DECIMAL(18, 2) NULL,
    DeidentifiedMaximumCharge DECIMAL(18, 2) NULL,
    DiscountedCashPrice DECIMAL(18, 2) NULL,
    AETNA509 DECIMAL(18, 2) NULL,
    AETNAAPCNSP729 DECIMAL(18, 2) NULL,
    AETNABP760 DECIMAL(18, 2) NULL,
    AETNAILPREFERRED139 DECIMAL(18, 2) NULL,
    BCBSBLUECHOICEOPTIONS727 DECIMAL(18, 2) NULL,
    BCBSBLUECHOICEPREFERRED479 DECIMAL(18, 2) NULL,
    BCBSPARINDEMNITYADP505 DECIMAL(18, 2) NULL,
    BCBSPPO424 DECIMAL(18, 2) NULL,
    CIGNAALTERNATIVE668 DECIMAL(18, 2) NULL,
    CIGNABROAD667 DECIMAL(18, 2) NULL,
    CIGNAPLUSNM682 DECIMAL(18, 2) NULL,
    HUMANAHMO299 DECIMAL(18, 2) NULL,
    HUMANAPPO145 DECIMAL(18, 2) NULL,
    UHCCORE346 DECIMAL(18, 2) NULL,
    UHCHMOPPO535 DECIMAL(18, 2) NULL,
    ChargeCode BIGINT NULL
);
