from pydantic import BaseModel, ValidationError
from typing import Optional



class UCMCCharges(BaseModel):
    LocationID :  Optional [int]
    SystemID :  Optional [int]
    LocationName :  Optional [str]
    CodeID :  Optional [str]
    DefaultItemCode :  Optional [str]
    ServiceDescription :  Optional [str] 
    CDM_Revenue_Code :  Optional [str]
    BillingCode :  Optional [str]
    CDM_Modifier :  Optional [str]
    grossCharge : Optional [float]
    discountedCashPrice : Optional [float]
    FSC_75_Price : Optional [float]
    FSC_75_Discounted_Cash_Price : Optional [float]
    FSC_171_Price : Optional [float]
    FSC_171_Discounted_Cash_Price : Optional [float]
    FSC_179_Price : Optional [float]
    FSC_179_Discounted_Cash_Price : Optional [float]
    FSC_178_Price : Optional [float]
    FSC_178_Discounted_Cash_Price : Optional [float]
    FSC_176_Price : Optional [float]
    FSC_176_Discounted_Cash_Price : Optional [float]
    FSC_174_Price : Optional [float]
    FSC_174_Discounted_Cash_Price : Optional [float]
    FSC_172_Price : Optional [float]
    FSC_172_Discounted_Cash_Price : Optional [float]
    FSC_70_Price : Optional [float]
    FSC_70_Discounted_Cash_Price : Optional [float]
    FSC_73_Price : Optional [float]
    FSC_73_Discounted_Cash_Price : Optional [float]
    FSC_77_Price : Optional [float]
    FSC_77_Discounted_Cash_Price : Optional [float]
    FSC_170_Price : Optional [float]
    FSC_170_Discounted_Cash_Price : Optional [float]