from pydantic import BaseModel, ValidationError
from typing import Optional




class LoyolaCharges(BaseModel):
    LocationID : Optional [int]
    SystemID : Optional [int ]
    LocationName : Optional [str]
    BillingCode : Optional [str]
    ServiceDescription : Optional [str]
    GrossCharge : Optional [float]
    DeidentifiedMaximumCharge : Optional [float]
    DeidentifiedMinimumCharge : Optional [float]
    DerivedContractedRate : Optional [float]
    DiscountedCashPrice : Optional [float]
    AetnaBetterHealthMedicaidHMO : Optional [float]
    AetnaCommercialHMOPOS : Optional [float]
    AetnaCommercialPPOOpenAccess : Optional [float]
    AetnaMedicaidHMO : Optional [float]
    AetnaMedicareAdvantageHMO : Optional [float]
    AetnaMedicareMedicareAdvantageHMO : Optional [float]
    AmbetterMedicaidHMO : Optional [float]
    BCBSCommercialHMOPOS : Optional [float]
    BlueCrossBlueShieldCommercialHMOPOS : Optional [float]
    BlueCrossBlueShieldCommercialPPOOpenAccess : Optional [float]
    BlueCrossBlueShieldIPACommercialHMOPOS : Optional [float]
    BlueCrossBlueShieldMedicaidMedicaidHMO : Optional [float]
    BlueCrossBlueShieldMedicareMedicareAdvantageHMO : Optional [float]
    CignaCommercialHMOPOS : Optional [float]
    CignaCommercialPPOOpenAccess : Optional [float]
    CignaMedicareAdvantageHMO : Optional [float]
    CountyCareMedicaidHMO : Optional [float]
    GEHACommercialHMOPOS : Optional [float]
    GenericCommercialother : Optional [float]
    HumanaCommercialHMOPOS : Optional [float]
    HumanaCommercialHMOPOS2nd : Optional [float]
    HumanaCommercialPPOOpenAccess : Optional [float]
    HumanaMedicareMedicareAdvantageHMO : Optional [float]
    IllinicareMedicaidHMO : Optional [float]
    MedicaidHMOOutofState : Optional [float]
    MedicaidMedicaid : Optional [float]
    MedicareAdvantageHMO : Optional [float]
    MedicareMedicare : Optional [float]
    MeridianMedicaidHMO : Optional [float]
    MolinaMedicaidHMO : Optional [float]
    OptumCommercialPPOOpenAccess : Optional [float]
    PhysiciansMutualCommercialother : Optional [float]
    TricareCommercialHMOPOS : Optional [float]
    Type : str
    UHCCommercialother : Optional [float]
    UMRCommercialPPOOpenAccess : Optional [float]
    UMRCommercialPPOOpenAccess2nd : Optional [float]
    UnitedHealhCareCommercialOther : Optional [float]
    UnitedHealthCareCommercialHMOPOS : Optional [float]
    UnitedHealthCareCommercialPPOOpenAccess : Optional [float]
    UnitedHealthCareMedicaidMedicaidHMO : Optional [float]
    UnitedHealthCareMedicaidMedicaidHMO2nd : Optional [float]
    UnitedHealthCareMedicareAdvantageHMO : Optional [float]
    UnitedHealthCareMedicareMedicareAdvantageHMO : Optional [float]
    WellcareMedicareMedicareAdvantageHMO : Optional [float]
    WorkersComp : Optional [float]